name: user_app
description: Rodafe app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  authentication_provider:
  bloc: ^9.0.0
  built_collection: ^5.1.1
  car_repository:
    path: ../../packages/car_repository
  equatable: ^2.0.5
  ferry: ^0.16.1+2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.2
  gql_http_link: ^1.1.0
  graphql_data_source:
  intl: ^0.20.2
  reactive_forms: ^18.1.1
  rodafe_ui:
    path: ../../packages/rodafe_ui
  shared_models:
  supabase: ^2.8.0
  supabase_auth_ui: ^0.5.5
  supabase_flutter: ^2.9.1
  user_repository:
    path: ../../packages/user_repository

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true
