name: shared_models
description: Shared models and enums for the Rodafe project
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0
